// Homework3/davchu/src/components/BarChart.vue
<template>
  <div class="bar-chart-wrapper">
    <button class="sort-button" @click="toggleSortReset">{{ buttonLabel }}</button>
    <div class="chart-container" ref="barContainer">
      <svg id="bar-svg"></svg>
    </div>
    <!-- Tooltip Element -->
    <div v-if="tooltipVisible" class="tooltip" :style="tooltipStyle">
      <strong>{{ tooltipData.category }}:</strong> {{ tooltipData.value }}
    </div>
  </div>
</template>

<script lang="ts">
import * as d3 from "d3";
import { debounce, isEmpty } from 'lodash';

interface CategoricalBar {
  category: string;
  value: number;
}

export default {
  name: 'BarChart',
  data() {
    return {
      bars: [] as CategoricalBar[], // Store the bar data
      originalBars: [] as CategoricalBar[], // Store original data to reset
      size: { width: 0, height: 0 },
      margin: { left: 80, right: 40, top: 50, bottom: 130 },
      xScale: null as any,
      buttonLabel: "Sort by Value", // Button label toggles between Sort and Reset
      tooltipVisible: false,
      tooltipData: { category: '', value: 0 },
      tooltipStyle: { left: '0px', top: '0px' }
    };
  },
  computed: {
    rerender() {
      return !isEmpty(this.bars) && this.size;
    }
  },
  created() {
    d3.csv('../../data/car_prices.csv').then((data: any[]) => {
      const validStateData = data.filter(d => /^[a-z]{2}$/.test(d.state));
      const stateCarCounts = d3.rollups(
        validStateData,
        v => v.length,
        d => d.state
      )
        .map(([state, count]) => ({ category: state, value: count }));

      this.bars = stateCarCounts;
      this.originalBars = [...stateCarCounts]; // Save a copy of the original data
      this.initChart();
    });
  },
  methods: {
    onResize() {
      const container = this.$refs.barContainer as HTMLElement;
      this.size.width = container.clientWidth;
      this.size.height = container.clientHeight;
      d3.select("#bar-svg").selectAll("*").remove(); // Clear previous chart
      this.initChart();
    },
    initChart() {
      const svg = d3.select("#bar-svg")
        .attr("viewBox", `0 0 ${this.size.width} ${this.size.height}`)
        .attr("width", "100%")
        .attr("height", "100%");

      const chartWidth = Math.max(this.size.width, this.bars.length * 10);
      svg.attr("width", chartWidth);

      const chartContainer = svg.append('g')
        .attr("transform", `translate(${this.margin.left}, ${this.margin.top})`);

      this.xScale = d3.scaleBand()
        .domain(this.bars.map(d => d.category))
        .range([0, chartWidth - this.margin.left - this.margin.right])
        .padding(0.1);

      const yScale = d3.scaleLinear()
        .domain([0, d3.max(this.bars, d => d.value)!])
        .range([this.size.height - this.margin.top - this.margin.bottom, 0]);

      // Chart Title
      svg.append('text')
        .attr('x', this.size.width / 2)
        .attr('y', this.margin.top / 2)
        .attr('text-anchor', 'middle')
        .style('font-size', '16px')
        .style('font-weight', 'bold')
        .text('Car Counts by State');

      // X-axis
      chartContainer.append('g')
        .attr('transform', `translate(0, ${this.size.height - this.margin.top - this.margin.bottom})`)
        .call(d3.axisBottom(this.xScale))
        .selectAll('text')
        .style('text-anchor', 'end')
        .style('font-size', '9px')
        .attr('x', 3);

      // Y-axis
      chartContainer.append('g')
        .call(d3.axisLeft(yScale));

      // X-axis label
      svg.append('text')
        .attr('x', this.size.width / 2)
        .attr('y', this.size.height - this.margin.bottom / 3)
        .attr('text-anchor', 'middle')
        .style('font-size', '14px')
        .style('font-weight', 'bold')
        .text('State');

      // Y-axis label
      svg.append('text')
        .attr('x', -this.size.height / 2)
        .attr('y', this.margin.left / 3)
        .attr('transform', 'rotate(-90)')
        .attr('text-anchor', 'middle')
        .style('font-size', '14px')
        .style('font-weight', 'bold')
        .text('Car Count');

        const padding = 5; // Padding area around each bar

        chartContainer.selectAll('.bar')
          .data(this.bars)
          .enter()
          .append('rect')
          .attr('class', 'hover-area')
          .attr('x', (d: CategoricalBar) => this.xScale(d.category)! - padding) // Expanding the area
          .attr('y', 0)
          .attr('width', (d: CategoricalBar) => this.xScale.bandwidth() + 2 * padding) // Expand the width
          .attr('height', this.size.height - this.margin.top - this.margin.bottom)
          .attr('fill', 'transparent') // Make the hover area invisible
          .on('mouseover', (event, d) => this.showTooltip(event, d))
          .on('mousemove', this.moveTooltip)
          .on('mouseout', this.hideTooltip)
          .on('click', (event, d) => {
            this.$emit('stateSelected', d.category);
          });

        chartContainer.selectAll('.bar')
          .data(this.bars)
          .enter()
          .append('rect')
          .attr('class', 'bar')
          .attr('x', (d: CategoricalBar) => this.xScale(d.category)!)
          .attr('y', (d: CategoricalBar) => yScale(d.value))
          .attr('width', this.xScale.bandwidth()) // Actual bar width
          .attr('height', (d: CategoricalBar) => this.size.height - this.margin.top - this.margin.bottom - yScale(d.value))
          .attr('fill', 'teal')
          .on('mouseover', (event, d) => this.showTooltip(event, d))
          .on('mousemove', this.moveTooltip)
          .on('mouseout', this.hideTooltip)
          .on('click', (event, d) => {
            this.$emit('stateSelected', d.category); // Emit selected state to parent
          });
      },
    showTooltip(event, data) {
      this.tooltipData = {
        category: data.category,
        value: data.value
      };
      this.tooltipVisible = true;
    },
    moveTooltip(event) {
      this.tooltipStyle = {
        left: `${event.pageX + 10}px`,
        top: `${event.pageY + 10}px`
      };
    },
    hideTooltip() {
      this.tooltipVisible = false;
    },
    toggleSortReset() {
      if (this.buttonLabel === "Sort by Value") {
        this.sortBars();
        this.buttonLabel = "Reset";
      } else {
        this.resetBars();
        this.buttonLabel = "Sort by Value";
      }
    },
    sortBars() {
      this.bars.sort((a, b) => b.value - a.value);
      this.xScale.domain(this.bars.map(d => d.category));

      d3.select("#bar-svg")
        .selectAll('.bar')
        .data(this.bars, d => d.category)
        .transition()
        .duration(750)
        .attr('x', (d: CategoricalBar) => this.xScale(d.category)!);

      d3.select("#bar-svg")
        .selectAll('.label')
        .data(this.bars, d => d.category)
        .transition()
        .duration(750)
        .attr('x', (d: CategoricalBar) => this.xScale(d.category)! + this.xScale.bandwidth() / 2);
    },
    resetBars() {
      this.bars = [...this.originalBars];
      this.xScale.domain(this.bars.map(d => d.category));

      d3.select("#bar-svg")
        .selectAll('.bar')
        .data(this.bars, d => d.category)
        .transition()
        .duration(750)
        .attr('x', (d: CategoricalBar) => this.xScale(d.category)!);

      d3.select("#bar-svg")
        .selectAll('.label')
        .data(this.bars, d => d.category)
        .transition()
        .duration(750)
        .attr('x', (d: CategoricalBar) => this.xScale(d.category)! + this.xScale.bandwidth() / 2);
    }
  },
  watch: {
    rerender(newSize) {
      if (!isEmpty(newSize)) {
        d3.select('#bar-svg').selectAll('*').remove();
        this.initChart();
      }
    }
  },
  mounted() {
    window.addEventListener('resize', debounce(this.onResize, 100));
    this.onResize();
  },
  beforeDestroy() {
    window.removeEventListener('resize', this.onResize);
  }
}
</script>

<style scoped>
.bar-chart-wrapper {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100vh;
}

.chart-container {
  display: flex;
  width: 48.6vw;  /* 10% smaller */
  height: 43.2vh; /* 10% smaller */
  overflow-x: auto;
  overflow-y: hidden;
  border: 1px solid #ccc;
  box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.2);
  border-radius: 8px;
  background-color: #f9f9f9;
  transform: translateX(20px); /* Move left by 10px */
}

.sort-button {
  margin-bottom: 16px;
  padding: 10px 20px;
  font-size: 16px;
  color: #fff;
  background-color: teal;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  transition: background-color 0.3s ease;
}

.sort-button:hover {
  background-color: #007b7b;
}

.tooltip {
  position: absolute;
  background-color: rgba(0, 0, 0, 0.7);
  color: white;
  padding: 8px;
  border-radius: 4px;
  font-size: 12px;
  pointer-events: none;
}
</style>

// Homework3/saikotamreddy/src/components/BarChart.tsx
import React from 'react'
import { useEffect, useState, useRef } from 'react';
import * as d3 from 'd3';
import dataFromJson from '../../data/demo.json';
import { isEmpty } from 'lodash';
import { useResizeObserver, useDebounceCallback } from 'usehooks-ts';

import { Bar, ComponentSize, Margin } from '../types';
interface CategoricalBar{
  category: string;
  fem_value: number;
  mal_value: number;
  all_value: number;
}



export default function BarChart({mentalDisorder, selectedYear, setSelectedYear}) {
  const [bars, setBars] = useState<CategoricalBar[]>([]);
  const barRef = useRef<HTMLDivElement>(null);
  const [size, setSize] = useState<ComponentSize>({ width: 0, height: 0 });
  const margin: Margin = { top: 40, right: 20, bottom: 80, left: 60 };
  const onResize = useDebounceCallback((size: ComponentSize) => setSize(size), 200)

  useResizeObserver({ ref: barRef, onResize });
  
  useEffect(() => {
    // For reading json file
    /*if (isEmpty(dataFromJson)) return;
    setBars(dataFromJson.data);*/
    
    // For reading csv file
    const dataFromCSV = async () => {
      try {
        console.log(mentalDisorder)
        const csvData = await d3.csv('../../data/Student Mental health.csv', d => {
          return {gender: d['Choose your gender'], year: d['Your current year of Study'].toLowerCase(), Depression: d['Do you have Depression?'], Anxiety: d['Do you have Anxiety?'], Panic: d['Do you have Panic attack?']};
        });
        let depressionCount=0
        let noDepressionCount=0
        //First value has depression count, second is no depression count
        let maleCount=[0,0]
        let femaleCount=[0,0]
        let year_list=['year 1', 'year 2', 'year 3','year 4']
        //First value is male with depression, 2nd is male with no depression, female with depression, female without depression
        let years={'year 1':[0,0,0,0], 'year 2':[0,0,0,0], 'year 3':[0,0,0,0], 'year 4':[0,0,0,0]}
        for(let student in csvData){
          if(csvData[student].gender==undefined){
            continue;
          }
          if(csvData[student].gender=='Male'){
            if(csvData[student][mentalDisorder]=='Yes'){
              depressionCount=depressionCount+1
              maleCount[0]=maleCount[0]+1
              years[csvData[student]['year'] as keyof typeof years][0]=years[csvData[student]['year'] as keyof typeof years][0]+1
            }
            else{
              noDepressionCount=noDepressionCount+1
              maleCount[1]=maleCount[1]+1
              years[csvData[student]['year'] as keyof typeof years][1]=years[csvData[student]['year'] as keyof typeof years][1]+1
            }
          }
          else{
            if(csvData[student][mentalDisorder]=='Yes'){
              depressionCount=depressionCount+1
              femaleCount[0]=femaleCount[0]+1
              years[csvData[student]['year'] as keyof typeof years][2]=years[csvData[student]['year'] as keyof typeof years][2]+1
            }
            else{
              noDepressionCount=noDepressionCount+1
              femaleCount[1]=femaleCount[1]+1
              years[csvData[student]['year'] as keyof typeof years][3]=years[csvData[student]['year'] as keyof typeof years][3]+1
            }
          }
        }
        let categories=
        [
          {category: 'All Years', all_value: (femaleCount[0]+maleCount[0])/(femaleCount[0]+femaleCount[1]+maleCount[0]+maleCount[1]), fem_value: femaleCount[0]/(femaleCount[0]+femaleCount[1]), mal_value: maleCount[0]/(maleCount[0]+maleCount[1])},
          {category: 'Year 1', all_value: (years['year 1'][0]+years['year 1'][2])/(years['year 1'][0]+years['year 1'][1]+years['year 1'][2]+years['year 1'][3]), fem_value: years['year 1'][2]/(years['year 1'][2]+years['year 1'][3]), mal_value: years['year 1'][0]/(years['year 1'][0]+years['year 1'][1])},
          {category: 'Year 2', all_value: (years['year 2'][0]+years['year 2'][2])/(years['year 2'][0]+years['year 2'][1]+years['year 2'][2]+years['year 2'][3]), fem_value: years['year 2'][2]/(years['year 2'][2]+years['year 2'][3]), mal_value: years['year 2'][0]/(years['year 2'][0]+years['year 2'][1])},
          {category: 'Year 3', all_value: (years['year 3'][0]+years['year 3'][2])/(years['year 3'][0]+years['year 3'][1]+years['year 3'][2]+years['year 3'][3]), fem_value: years['year 3'][2]/(years['year 3'][2]+years['year 3'][3]), mal_value: years['year 3'][0]/(years['year 3'][0]+years['year 3'][1])},
          {category: 'Year 4', all_value: (years['year 4'][0]+years['year 4'][2])/(years['year 4'][0]+years['year 4'][1]+years['year 4'][2]+years['year 4'][3]), fem_value: years['year 4'][2]/(years['year 4'][2]+years['year 4'][3]), mal_value: years['year 4'][0]/(years['year 4'][0]+years['year 4'][1])},
        
        ]
        setBars(categories);
      } catch (error) {
        console.error('Error loading CSV:', error);
      }
    } 
    dataFromCSV();
  }, [mentalDisorder])

  useEffect(() => {
    if (isEmpty(bars)) return;
    if (size.width === 0 || size.height === 0) return;
    d3.select('#bar-svg').selectAll('*').remove();
    initChart();
  }, [bars, size, selectedYear])

  function initChart() {

    let chartContainer = d3.select('#bar-svg');

    let yExtents = d3.extent(bars.map((d: CategoricalBar) => Math.max(d.fem_value, d.all_value, d.mal_value) as number)) as [number, number];
    let xCategories: string[] = [...new Set(bars.map((d: CategoricalBar) => d.category as string))];

    let xScale = d3.scaleBand()
      .rangeRound([margin.left, size.width - margin.right])
      .domain(xCategories)
      .padding(0.2);

    let yScale = d3.scaleLinear()
      .range([size.height - margin.bottom, margin.top])
      .domain([0, yExtents[1]]);

    const xAxis = chartContainer.append('g')
      .attr('transform', `translate(0, ${size.height - margin.bottom})`)
      .call(d3.axisBottom(xScale));

    const yAxis = chartContainer.append('g')
      .attr('transform', `translate(${margin.left}, 0)`)
      .call(d3.axisLeft(yScale));

    const yLabel = chartContainer.append('g')
      .attr('transform', `translate(${margin.left / 4}, ${size.height / 1.5}) rotate(-90)`)
      .append('text')
      .text('Percent of Group Who Have '+String(mentalDisorder).charAt(0).toUpperCase()+String(mentalDisorder).slice(1))
      .style('font-size', '.8rem');

    const xLabel = chartContainer.append('g')
      .attr('transform', `translate(${(size.width - margin.left) / 2}, ${size.height - margin.top})`)
      .append('text')
      .text('Mental Health Issues')
      .style('font-size', '.8rem');

    const chartBars = chartContainer.append('g')
      .selectAll('g')
      .data<CategoricalBar>(bars)
      .join('g')
      .attr('transform', (d: CategoricalBar) => `translate(${xScale(d.category)}, 0)`);


      const updateHighlighting = () => {
        chartBars.selectAll('rect')
          .style('opacity', (d) => {
            // Dim bars if they do not belong to the selected category
            return selectedYear && d.category !== selectedYear ? 0.3 : 1;
          });
      };
      const tooltip = d3.select("body").append("div")
      .attr("class", "tooltip")
      .style("position", "absolute")
      .style("background", "rgba(0, 0, 0, 0.7)")
      .style("color", "#fff")
      .style("padding", "5px")
      .style("border-radius", "4px")
      .style("font-size", "0.8rem")
      .style("pointer-events", "none")
      .style("opacity", 0);

    // Function to show the tooltip
    const showTooltip = (event, d, gender, value) => {
      tooltip.style("opacity", 1)
        .html(`Year: ${d.category}<br>Gender: ${gender}<br>Percent of Population: ${value}`)
        .style("left", `${event.pageX + 10}px`)
        .style("top", `${event.pageY - 28}px`);
    };

    // Function to hide the tooltip
    const hideTooltip = () => {
      tooltip.style("opacity", 0);
    };
      
      // Handle bar click event to update the selected category
      chartBars.on('click', function(event, d) {
        // Toggle selection or clear if the same category is clicked again
        setSelectedYear(selectedYear === d.category ? null : d.category);
        updateHighlighting();
        hideTooltip();
      });
    
    // First bar (pink)
    chartBars.append('rect')
      .attr('x', xScale.bandwidth() / 3)
      .attr('y', (d: CategoricalBar) => yScale(d.fem_value) as number)
      .attr('width', xScale.bandwidth() / 3) // Half the bandwidth for the first bar
      .attr('height', (d: CategoricalBar) => Math.abs(yScale(0) - yScale(d.fem_value)))
      .attr('fill', 'pink')
      .on("mouseover", (event, d) => showTooltip(event, d, "Female", Math.round(d.fem_value*1000)/1000))
      .on("mouseout", hideTooltip);

    // Second bar (blue)
    chartBars.append('rect')
      .attr('x', 2*xScale.bandwidth() / 3) // Shift the second bar to the right
      .attr('y', (d: CategoricalBar) => yScale(d.mal_value) as number)
      .attr('width', xScale.bandwidth() /3)
      .attr('height', (d: CategoricalBar) => Math.abs(yScale(0) - yScale(d.mal_value)))
      .attr('fill', 'blue')
      .on("mouseover", (event, d) => showTooltip(event, d, "Male", Math.round(d.mal_value*1000)/1000))
      .on("mouseout", hideTooltip);

      chartBars.append('rect')
      .attr('x', 0) // Shift the second bar to the right
      .attr('y', (d: CategoricalBar) => yScale(d.all_value) as number)
      .attr('width', xScale.bandwidth() / 3)
      .attr('height', (d: CategoricalBar) => Math.abs(yScale(0) - yScale(d.all_value)))
      .attr('fill', 'purple')
      .on("mouseover", (event, d) => showTooltip(event, d, "Both Genders", Math.round(d.all_value*1000)/1000))
      .on("mouseout", hideTooltip);
    
      updateHighlighting();

    const title = chartContainer.append('g')
      .append('text')
      .attr('transform', `translate(${size.width / 2}, ${size.height - margin.top + 15})`)
      .attr('dy', '0.5rem')
      .style('text-anchor', 'middle')
      .style('font-weight', 'bold')
      .text('Breakdown of Mental Issues By Gendered Population');

    const legend = chartContainer.append('g')
      .attr('transform', `translate(${size.width - margin.right - 90}, ${margin.top})`);

    legend.append('rect')
      .attr('x', 0)
      .attr('y', 25)
      .attr('width', 20)
      .attr('height', 20)
      .attr('fill', 'pink');

    legend.append('text')
      .attr('x', 25)
      .attr('y', 40)
      .text('Female')
      .style('font-size', '.8rem');

    legend.append('rect')
      .attr('x', 0)
      .attr('y', 50)
      .attr('width', 20)
      .attr('height', 20)
      .attr('fill', 'blue');

    legend.append('text')
      .attr('x', 25)
      .attr('y', 65)
      .text('Male')
      .style('font-size', '.8rem');

      legend.append('rect')
      .attr('x', 0)
      .attr('y', 0)
      .attr('width', 20)
      .attr('height', 20)
      .attr('fill', 'purple');

    legend.append('text')
      .attr('x', 25)
      .attr('y', 15)
      .text('Both Genders')
      .style('font-size', '.8rem');
}

  return (
    <>
      <div ref={barRef} className='chart-container'>
        <svg id='bar-svg' width='100%' height='100%'></svg>
      </div>
    </>
  )
}
