// Homework2/disnarayan/React-Template/src/components/ScatterPlot.tsx
import React, { useEffect, useRef, useState } from 'react';
import * as d3 from 'd3';
import { csv } from 'd3-fetch';

interface DataPoint {
  age: number;
  cgpa: number;
  gender: string;
  depression: boolean;
  course: string;
}

const ScatterPlot: React.FC = () => {
  const [data, setData] = useState<DataPoint[]>([]);
  const svgRef = useRef<SVGSVGElement>(null);

  useEffect(() => {
    csv('/data/StudentMentalhealth.csv').then((csvData) => {
      const scatterData = csvData.map(row => ({
        age: +row['Age'],
        cgpa: parseCGPA(row['What is your CGPA?']),
        gender: row['Choose your gender'],
        depression: row['Do you have Depression?'] === 'Yes',
        course: row['What is your course?']
      }));
      setData(scatterData);
    });
  }, []);

  const parseCGPA = (cgpaRange: string): number => {
    const [min, max] = cgpaRange.split(' - ').map(Number);
    return (min + max) / 2;
  };

  useEffect(() => {
    if (data.length === 0 || !svgRef.current) return;

    const margin = { top: 50, right: 200, bottom: 60, left: 80 };
    const width = 900 - margin.left - margin.right;
    const height = 500 - margin.top - margin.bottom;

    d3.select(svgRef.current).selectAll("*").remove();

    const svg = d3.select(svgRef.current)
      .attr('width', width + margin.left + margin.right)
      .attr('height', height + margin.top + margin.bottom)
      .append('g')
      .attr('transform', `translate(${margin.left},${margin.top})`);

    const x = d3.scaleLinear()
      .domain([d3.min(data, d => d.age) || 0, d3.max(data, d => d.age) || 0])
      .range([0, width]);

    const y = d3.scaleLinear()
      .domain([d3.min(data, d => d.cgpa) || 0, d3.max(data, d => d.cgpa) || 0])
      .range([height, 0]);

    const courses = Array.from(new Set(data.map(d => d.course)));
    const color = d3.scaleOrdinal<string>()
      .domain(courses)
      .range(d3.schemeCategory10);

    const getSymbol = (gender: string): d3.SymbolType => {
      return gender === 'Male' ? d3.symbolSquare : d3.symbolCircle;
    };

    const getOpacity = (depression: boolean): number => {
      return depression ? 1 : 0.5;
    };

    svg.append('g')
      .attr('transform', `translate(0,${height})`)
      .call(d3.axisBottom(x));

    svg.append('g')
      .call(d3.axisLeft(y));

    svg.selectAll('.point')
      .data(data)
      .enter()
      .append('path')
      .attr('class', 'point')
      .attr('d', d => d3.symbol().type(getSymbol(d.gender)).size(100)() || '')
      .attr('transform', d => `translate(${x(d.age)},${y(d.cgpa)})`)
      .style('fill', d => color(d.course))
      .style('opacity', d => getOpacity(d.depression))
      .on('mouseover', (event, d) => {
        const tooltip = d3.select('#tooltip');
        tooltip.transition().duration(200).style('opacity', 0.9);
        tooltip.html(`Age: ${d.age}<br/>CGPA: ${d.cgpa.toFixed(2)}<br/>Gender: ${d.gender}<br/>Course: ${d.course}<br/>Depression: ${d.depression ? 'Yes' : 'No'}`)
          .style('left', `${event.pageX}px`)
          .style('top', `${event.pageY - 28}px`);
      })
      .on('mouseout', () => {
        d3.select('#tooltip').transition().duration(500).style('opacity', 0);
      });

    // X-axis label
    svg.append('text')
      .attr('x', width / 2)
      .attr('y', height + margin.bottom - 10)
      .attr('text-anchor', 'middle')
      .text('Age');

    // Y-axis label
    svg.append('text')
      .attr('transform', 'rotate(-90)')
      .attr('y', 0 - margin.left)
      .attr('x', 0 - (height / 2))
      .attr('dy', '1em')
      .style('text-anchor', 'middle')
      .text('CGPA');

    // Chart title
    svg.append('text')
      .attr('x', width / 2)
      .attr('y', 0 - (margin.top / 2))
      .attr('text-anchor', 'middle')
      .style('font-size', '16px')
      .style('text-decoration', 'underline')
      .text('Age vs CGPA Scatter Plot (Grouped by Course)');

    // Legend
    const legend = svg.append('g')
      .attr('font-family', 'sans-serif')
      .attr('font-size', 10)
      .attr('text-anchor', 'start')
      .selectAll('g')
      .data([...courses, 'Male', 'Female', 'Depression', 'No Depression'])
      .join('g')
      .attr('transform', (d, i) => `translate(${width + 20},${i * 20})`);

    legend.append('rect')
      .attr('x', 0)
      .attr('width', 19)
      .attr('height', 19)
      .attr('fill', d => {
        if (courses.includes(d)) return color(d);
        return 'white';
      })
      .attr('stroke', 'black');

    legend.append('text')
      .attr('x', 24)
      .attr('y', 9.5)
      .attr('dy', '0.32em')
      .text(d => d);

    // Add symbols for gender and depression
    legend.filter(d => d === 'Male' || d === 'Female')
      .append('path')
      .attr('d', d => d3.symbol().type(getSymbol(d)).size(100)() || '')
      .attr('transform', 'translate(9.5, 9.5)')
      .style('fill', 'black');

    legend.filter(d => d === 'Depression' || d === 'No Depression')
      .append('circle')
      .attr('cx', 9.5)
      .attr('cy', 9.5)
      .attr('r', 6)
      .style('fill', 'black')
      .style('opacity', d => d === 'Depression' ? 1 : 0.5);

  }, [data]);

  return (
    <div className="chart-container">
      <svg ref={svgRef}></svg>
      <div id="tooltip" style={{
        position: 'absolute',
        textAlign: 'center',
        padding: '8px',
        font: '12px sans-serif',
        background: 'lightsteelblue',
        border: '0px',
        borderRadius: '8px',
        pointerEvents: 'none',
        opacity: 0,
      }}></div>
    </div>
  );
};

export default ScatterPlot;

// Homework3/zlihuang/src/components/ScatterPlot.vue
<script lang="ts">
import * as d3 from "d3";
import { isEmpty, debounce } from 'lodash';

export default {
    props: {
        filteredData: {
            type: Object,
            default: null
        }
    },
    data() {
        return {
            mergedData: [] as d3.DSVRowString<string>[],
            aggregatedDalcData: [] as { Dalc: number; G3: number; count: number }[], 
            aggregatedWalcData: [] as { Walc: number; G3: number; count: number }[], 
            size: { width: 0, height: 0 }, 
            margin: { left: 50, right: 20, top: 20, bottom: 80 },
        };
    },
    created() {
        this.loadAndMergeData();
    },
    methods: {
        onResize() {
            const target = this.$refs.scatterContainer as HTMLElement;
            if (target) {
                this.size = { width: target.clientWidth - 30, height: target.clientHeight };
                d3.select('#scatter-svg').selectAll('*').remove(); 
                this.initScatterPlot(); 
            }
        },
        async loadAndMergeData() {
            try {
                const matData = await d3.csv('data/student-mat.csv');
                const porData = await d3.csv('data/student-por.csv');
                
                const commonKeys = ['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian'];
                
                const combinedData = matData.map(student => {
                    const correspondingPorStudent = porData.find(porStudent =>
                        commonKeys.every(key => student[key] === porStudent[key])
                    );
                    return correspondingPorStudent ? { ...student, ...correspondingPorStudent } : null;
                });
                this.mergedData = combinedData.filter(student => student !== null);
                this.aggregateData();
                this.initScatterPlot();
            } catch (error) {
                console.error("Error loading or merging data:", error);
            }
        },
        aggregateData() {
            const dalcDataMap = new Map();
            const walcDataMap = new Map();

            this.mergedData.forEach(d => {
                const dalcKey = `${d.Dalc}-${d.G3}`;
                const walcKey = `${d.Walc}-${d.G3}`;

                if (dalcDataMap.has(dalcKey)) {
                    dalcDataMap.get(dalcKey).count += 1;
                } else {
                    dalcDataMap.set(dalcKey, { Dalc: +d.Dalc, G3: +d.G3, count: 1 });
                }

                if (walcDataMap.has(walcKey)) {
                    walcDataMap.get(walcKey).count += 1;
                } else {
                    walcDataMap.set(walcKey, { Walc: +d.Walc, G3: +d.G3, count: 1 });
                }
            });

            this.aggregatedDalcData = Array.from(dalcDataMap.values());
            this.aggregatedWalcData = Array.from(walcDataMap.values());

        },
        initScatterPlot() {
            const svg = d3.select("#scatter-svg");
            const width = this.size.width - this.margin.left - this.margin.right;
            const height = this.size.height - this.margin.top - this.margin.bottom;


            const filteredDalcData = this.filteredData && this.filteredData.type === 'Dalc'
                ? this.aggregatedDalcData.filter(d => d.Dalc === +this.filteredData.level)
                : this.aggregatedDalcData;

            const filteredWalcData = this.filteredData && this.filteredData.type === 'Walc'
                ? this.aggregatedWalcData.filter(d => d.Walc === +this.filteredData.level)
                : this.aggregatedWalcData;

            svg.selectAll("*").remove();


            const g = svg.append("g")
                .attr("transform", `translate(${this.margin.left},${this.margin.top})`);

 
            const xScale = d3.scaleLinear()
                .domain([1, 5]) 
                .range([0, width]);

            const yScale = d3.scaleLinear()
                .domain([0, 20]) 
                .range([height, 0]);
            
            const maxCount = Math.max(
                d3.max(this.aggregatedDalcData, d => d.count) || 1,
                d3.max(this.aggregatedWalcData, d => d.count) || 1
            );
            const radiusScale = d3.scaleSqrt()
                .domain([1, maxCount]) 
                .range([5, 15]); 

            const xAxis = d3.axisBottom(xScale).ticks(5);
            const yAxis = d3.axisLeft(yScale).ticks(10);
            const gap=20;

            g.append("g")
                .attr("transform", `translate(0,${height})`)
                .call(xAxis)
                .append("text")
                .attr("x", width / 2)
                .attr("y", this.margin.bottom - 40)
                .attr("fill", "black")
                .style("font-size", "16px")
                .style('text-anchor', 'middle')
                .text("Alcohol Consumption");

            g.append("g")
                .attr("transform", `translate(-10, 0)`) 
                .call(yAxis)
                .append("text")
                .attr("transform", "rotate(-90)")
                .attr("y", -this.margin.left + 25)
                .attr("x", -height / 2)
                .attr("fill", "black")
                .style("font-size", "16px")
                .style("text-anchor", "middle")
                .text("Final Grade (G3)");
        
            g.append("g")
                .attr("transform", `translate(0,${height})`)
                .append("text")
                .attr("x", width / 2)
                .attr("y", this.margin.bottom - 20)
                .attr("fill", "black")
                .style("font-size", "16px")
                .style('font-weight', 'bold')
                .style('text-anchor', 'middle')
                .text("Alcohol Consumption vs Final Grades");

            const tooltip = d3.select("body").append("div")
                .attr("class", "tooltip")
                .style("position", "absolute")
                .style("visibility", "hidden")
                .style("padding", "8px")
                .style("background", "rgba(0, 0, 0, 0.7)")
                .style("border-radius", "4px")
                .style("color", "white")
                .style("font-size", "12px");

            
            const dalcPoints = g.selectAll(".dalc-point")
                .data(filteredDalcData, (d: any) => d.Dalc);

            dalcPoints.enter()
                .append("circle")
                .attr("class", "dalc-point")
                .attr("cx", d => xScale(+d.Dalc))
                .attr("cy", d => yScale(+d.G3))
                .attr("r", 0) 
                .attr("fill", "blue")
                .attr("opacity", 0)
                .on("mouseover", (event, d) => {
                    tooltip.html(`Dalc (Workday): ${d.Dalc}<br>Final Grade: ${d.G3}<br>Count: ${d.count}`)
                        .style("visibility", "visible");
                })
                .on("mousemove", event => {
                    tooltip.style("top", (event.pageY - 10) + "px")
                        .style("left", (event.pageX + 10) + "px");
                })
                .on("mouseout", () => tooltip.style("visibility", "hidden"))
                .transition()
                .duration(500)
                .attr("r", d => radiusScale(d.count)) 
                .attr("opacity", 0.7);
                
            dalcPoints.exit()
                .transition()
                .duration(500)
                .attr("r", 0) 
                .attr("opacity", 0)
                .remove();

            const walcPoints = g.selectAll(".walc-point")
                .data(filteredWalcData, (d: any) => d.Walc);

            walcPoints.enter()
                .append("circle")
                .attr("class", "walc-point")
                .attr("cx", d => xScale(+d.Walc)+gap)
                .attr("cy", d => yScale(+d.G3))
                .attr("r", 0) 
                .attr("fill", "orange")
                .attr("opacity", 0)
                .on("mouseover", (event, d) => {
                tooltip.html(`Walc (Weekend): ${d.Walc}<br>Final Grade: ${d.G3}<br>Count: ${d.count}`)
                    .style("visibility", "visible");
                })
                .on("mousemove", event => {
                tooltip.style("top", (event.pageY - 10) + "px")
                    .style("left", (event.pageX + 10) + "px");
                })
                .on("mouseout", () => tooltip.style("visibility", "hidden"))
                .transition()
                .duration(500)
                .attr("r", d => radiusScale(d.count)) 
                .attr("opacity", 0.7);

            walcPoints.exit()
                .transition()
                .duration(500)
                .attr("r", 0)
                .attr("opacity", 0)
                .remove();

            const legend = svg.append("g")
                .attr("transform", `translate(${width - 50}, ${this.margin.top})`); 

            // Dalc legend entry
            legend.append("circle")
                .attr("cx", 15)
                .attr("cy", -10)
                .attr("r", 5)
                .attr("fill", "blue");
            legend.append("text")
                .attr("x", 25)
                .attr("y", -10)
                .text("Dalc (Workday)")
                .style("alignment-baseline", "middle");

            // Walc legend entry
            legend.append("circle")
                .attr("cx", 15)
                .attr("cy", 10)
                .attr("r", 5)
                .attr("fill", "orange");
            legend.append("text")
                .attr("x", 25)
                .attr("y", 10)
                .text("Walc (Weekend)")
                .style("alignment-baseline", "middle");
        }
    },
    watch: {
        rerender(newSize) {
            if (!isEmpty(newSize)) {
                d3.select('#scatter-svg').selectAll('*').remove();
                this.initScatterPlot(); 
            }
        },
        filteredData(newFilter) {
            d3.select('#scatter-svg').selectAll('*').remove();
            this.initScatterPlot();
        }
    },
    mounted() {
        window.addEventListener('resize', debounce(this.onResize, 100));
        this.onResize();
    },
    beforeDestroy() {
        window.removeEventListener('resize', this.onResize);
    }
}
</script>

<template>
    <div class="chart-container d-flex" ref="scatterContainer">
        <svg id="scatter-svg" width="100%" height="100%"></svg>
    </div>
</template>

<style scoped>
.chart-container {
    height: 100%;
    width: 100%;
}
</style>
