// Homework3/davchu/src/components/BarChart.vue
<template>
  <div class="bar-chart-wrapper">
    <button class="sort-button" @click="toggleSortReset">{{ buttonLabel }}</button>
    <div class="chart-container" ref="barContainer">
      <svg id="bar-svg"></svg>
    </div>
    <!-- Tooltip Element -->
    <div v-if="tooltipVisible" class="tooltip" :style="tooltipStyle">
      <strong>{{ tooltipData.category }}:</strong> {{ tooltipData.value }}
    </div>
  </div>
</template>

<script lang="ts">
import * as d3 from "d3";
import { debounce, isEmpty } from 'lodash';

interface CategoricalBar {
  category: string;
  value: number;
}

export default {
  name: 'BarChart',
  data() {
    return {
      bars: [] as CategoricalBar[], // Store the bar data
      originalBars: [] as CategoricalBar[], // Store original data to reset
      size: { width: 0, height: 0 },
      margin: { left: 80, right: 40, top: 50, bottom: 130 },
      xScale: null as any,
      buttonLabel: "Sort by Value", // Button label toggles between Sort and Reset
      tooltipVisible: false,
      tooltipData: { category: '', value: 0 },
      tooltipStyle: { left: '0px', top: '0px' }
    };
  },
  computed: {
    rerender() {
      return !isEmpty(this.bars) && this.size;
    }
  },
  created() {
    d3.csv('../../data/car_prices.csv').then((data: any[]) => {
      const validStateData = data.filter(d => /^[a-z]{2}$/.test(d.state));
      const stateCarCounts = d3.rollups(
        validStateData,
        v => v.length,
        d => d.state
      )
        .map(([state, count]) => ({ category: state, value: count }));

      this.bars = stateCarCounts;
      this.originalBars = [...stateCarCounts]; // Save a copy of the original data
      this.initChart();
    });
  },
  methods: {
    onResize() {
      const container = this.$refs.barContainer as HTMLElement;
      this.size.width = container.clientWidth;
      this.size.height = container.clientHeight;
      d3.select("#bar-svg").selectAll("*").remove(); // Clear previous chart
      this.initChart();
    },
    initChart() {
      const svg = d3.select("#bar-svg")
        .attr("viewBox", `0 0 ${this.size.width} ${this.size.height}`)
        .attr("width", "100%")
        .attr("height", "100%");

      const chartWidth = Math.max(this.size.width, this.bars.length * 10);
      svg.attr("width", chartWidth);

      const chartContainer = svg.append('g')
        .attr("transform", `translate(${this.margin.left}, ${this.margin.top})`);

      this.xScale = d3.scaleBand()
        .domain(this.bars.map(d => d.category))
        .range([0, chartWidth - this.margin.left - this.margin.right])
        .padding(0.1);

      const yScale = d3.scaleLinear()
        .domain([0, d3.max(this.bars, d => d.value)!])
        .range([this.size.height - this.margin.top - this.margin.bottom, 0]);

      // Chart Title
      svg.append('text')
        .attr('x', this.size.width / 2)
        .attr('y', this.margin.top / 2)
        .attr('text-anchor', 'middle')
        .style('font-size', '16px')
        .style('font-weight', 'bold')
        .text('Car Counts by State');

      // X-axis
      chartContainer.append('g')
        .attr('transform', `translate(0, ${this.size.height - this.margin.top - this.margin.bottom})`)
        .call(d3.axisBottom(this.xScale))
        .selectAll('text')
        .style('text-anchor', 'end')
        .style('font-size', '9px')
        .attr('x', 3);

      // Y-axis
      chartContainer.append('g')
        .call(d3.axisLeft(yScale));

      // X-axis label
      svg.append('text')
        .attr('x', this.size.width / 2)
        .attr('y', this.size.height - this.margin.bottom / 3)
        .attr('text-anchor', 'middle')
        .style('font-size', '14px')
        .style('font-weight', 'bold')
        .text('State');

      // Y-axis label
      svg.append('text')
        .attr('x', -this.size.height / 2)
        .attr('y', this.margin.left / 3)
        .attr('transform', 'rotate(-90)')
        .attr('text-anchor', 'middle')
        .style('font-size', '14px')
        .style('font-weight', 'bold')
        .text('Car Count');

        const padding = 5; // Padding area around each bar

        chartContainer.selectAll('.bar')
          .data(this.bars)
          .enter()
          .append('rect')
          .attr('class', 'hover-area')
          .attr('x', (d: CategoricalBar) => this.xScale(d.category)! - padding) // Expanding the area
          .attr('y', 0)
          .attr('width', (d: CategoricalBar) => this.xScale.bandwidth() + 2 * padding) // Expand the width
          .attr('height', this.size.height - this.margin.top - this.margin.bottom)
          .attr('fill', 'transparent') // Make the hover area invisible
          .on('mouseover', (event, d) => this.showTooltip(event, d))
          .on('mousemove', this.moveTooltip)
          .on('mouseout', this.hideTooltip)
          .on('click', (event, d) => {
            this.$emit('stateSelected', d.category);
          });

        chartContainer.selectAll('.bar')
          .data(this.bars)
          .enter()
          .append('rect')
          .attr('class', 'bar')
          .attr('x', (d: CategoricalBar) => this.xScale(d.category)!)
          .attr('y', (d: CategoricalBar) => yScale(d.value))
          .attr('width', this.xScale.bandwidth()) // Actual bar width
          .attr('height', (d: CategoricalBar) => this.size.height - this.margin.top - this.margin.bottom - yScale(d.value))
          .attr('fill', 'teal')
          .on('mouseover', (event, d) => this.showTooltip(event, d))
          .on('mousemove', this.moveTooltip)
          .on('mouseout', this.hideTooltip)
          .on('click', (event, d) => {
            this.$emit('stateSelected', d.category); // Emit selected state to parent
          });
      },
    showTooltip(event, data) {
      this.tooltipData = {
        category: data.category,
        value: data.value
      };
      this.tooltipVisible = true;
    },
    moveTooltip(event) {
      this.tooltipStyle = {
        left: `${event.pageX + 10}px`,
        top: `${event.pageY + 10}px`
      };
    },
    hideTooltip() {
      this.tooltipVisible = false;
    },
    toggleSortReset() {
      if (this.buttonLabel === "Sort by Value") {
        this.sortBars();
        this.buttonLabel = "Reset";
      } else {
        this.resetBars();
        this.buttonLabel = "Sort by Value";
      }
    },
    sortBars() {
      this.bars.sort((a, b) => b.value - a.value);
      this.xScale.domain(this.bars.map(d => d.category));

      d3.select("#bar-svg")
        .selectAll('.bar')
        .data(this.bars, d => d.category)
        .transition()
        .duration(750)
        .attr('x', (d: CategoricalBar) => this.xScale(d.category)!);

      d3.select("#bar-svg")
        .selectAll('.label')
        .data(this.bars, d => d.category)
        .transition()
        .duration(750)
        .attr('x', (d: CategoricalBar) => this.xScale(d.category)! + this.xScale.bandwidth() / 2);
    },
    resetBars() {
      this.bars = [...this.originalBars];
      this.xScale.domain(this.bars.map(d => d.category));

      d3.select("#bar-svg")
        .selectAll('.bar')
        .data(this.bars, d => d.category)
        .transition()
        .duration(750)
        .attr('x', (d: CategoricalBar) => this.xScale(d.category)!);

      d3.select("#bar-svg")
        .selectAll('.label')
        .data(this.bars, d => d.category)
        .transition()
        .duration(750)
        .attr('x', (d: CategoricalBar) => this.xScale(d.category)! + this.xScale.bandwidth() / 2);
    }
  },
  watch: {
    rerender(newSize) {
      if (!isEmpty(newSize)) {
        d3.select('#bar-svg').selectAll('*').remove();
        this.initChart();
      }
    }
  },
  mounted() {
    window.addEventListener('resize', debounce(this.onResize, 100));
    this.onResize();
  },
  beforeDestroy() {
    window.removeEventListener('resize', this.onResize);
  }
}
</script>

<style scoped>
.bar-chart-wrapper {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100vh;
}

.chart-container {
  display: flex;
  width: 48.6vw;  /* 10% smaller */
  height: 43.2vh; /* 10% smaller */
  overflow-x: auto;
  overflow-y: hidden;
  border: 1px solid #ccc;
  box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.2);
  border-radius: 8px;
  background-color: #f9f9f9;
  transform: translateX(20px); /* Move left by 10px */
}

.sort-button {
  margin-bottom: 16px;
  padding: 10px 20px;
  font-size: 16px;
  color: #fff;
  background-color: teal;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  transition: background-color 0.3s ease;
}

.sort-button:hover {
  background-color: #007b7b;
}

.tooltip {
  position: absolute;
  background-color: rgba(0, 0, 0, 0.7);
  color: white;
  padding: 8px;
  border-radius: 4px;
  font-size: 12px;
  pointer-events: none;
}
</style>

// Homework3/yuhwei/src/components/BarChart.tsx
import React, { useEffect, useState, useRef } from 'react';
import * as d3 from 'd3';
import { isEmpty, max } from 'lodash';
import { useResizeObserver, useDebounceCallback } from 'usehooks-ts';
import { ComponentSize, Margin } from '../types';

export default function Example({ selectedBar, setSelectedBar }) {
  const [bars, setBars] = useState([]);
  const barRef = useRef<HTMLDivElement>(null);
  const [size, setSize] = useState<ComponentSize>({ width: 0, height: 0 });
  const margin: Margin = { top: 20, right: 150, bottom: 100, left: 150 }; 
  const onResize = useDebounceCallback((size: ComponentSize) => setSize(size), 20);
  const [stacked, setStacked] = useState(false);


  useResizeObserver({ ref: barRef, onResize });

  useEffect(() => {
    const dataFromCSV = async () => {
      try {
        const csvData = await d3.csv('../../data/student-por.csv', d => ({
          totalEdu: +d.Medu + +d.Fedu, 
          Dalc: +d.Dalc, 
          Walc: +d.Walc 
        }));
        setBars(csvData);
      } catch (error) {
        console.error('Error loading CSV:', error);
      }
    };
    dataFromCSV();
  }, []);

  useEffect(() => {
    if (isEmpty(bars)) return;
    if (size.width === 0 || size.height === 0) return;
    d3.select('#bar-svg').selectAll('*').remove();
    initChart();
  }, [bars, size]);

  function initChart() {
    const chartContainer = d3.select('#bar-svg');

    const groupedData = d3.rollups(
      bars,
      v => ({
        DalcPerCapita: d3.sum(v, d => d.Dalc) / v.length,
        WalcPerCapita: d3.sum(v, d => d.Walc) / v.length,
      }),
      d => {
        const totalEdu = d.totalEdu;
        if (totalEdu <= 2) return '0-2';
        if (totalEdu <= 5) return '3-5';
        if (totalEdu <= 8) return '6-8';
        return '9+';
      }
    ).map(([key, value]) => ({ key, ...value }))
     .sort((a, b) => ['0-2', '3-5', '6-8', '9+'].indexOf(a.key) - ['0-2', '3-5', '6-8', '9+'].indexOf(b.key));

    const minValue = d3.min(groupedData, d => Math.min(d.DalcPerCapita, d.WalcPerCapita));
    const maxValue = d3.max(groupedData, d => Math.max(d.DalcPerCapita, d.WalcPerCapita));

    const xScale = d3.scaleLinear()
      .domain([0, maxValue]) 
      .range([margin.left, size.width - margin.right]);

    const yScale = d3.scaleBand()
      .domain(groupedData.map(d => d.key))
      .range([size.height - margin.bottom, margin.top])
      .padding(0.4);

    chartContainer.append('g')
      .attr('transform', `translate(0, ${size.height - margin.bottom})`)
      .call(d3.axisBottom(xScale));

    chartContainer.append('text')
      .attr('transform', `translate(${(size.width - margin.left) / 2 + margin.left}, ${size.height - margin.bottom + 40})`)
      .style('text-anchor', 'middle')
      .text('Alcohol Consumption');

    chartContainer.append('g')
      .attr('transform', `translate(${margin.left}, 0)`)
      .call(d3.axisLeft(yScale));

    chartContainer.append('text')
      .attr('transform', 'rotate(-90)')
      .attr('y', margin.left - 60)
      .attr('x', -(size.height / 2))
      .attr('dy', '1em')
      .style('text-anchor', 'middle')
      .text('Parental Education Levels');
    
    const tooltip = d3.select(barRef.current)
      .append('div')
      .attr('class', 'tooltip')
      .style('opacity', 0)
      .style('position', 'absolute')
      .style('background', 'white')
      .style('border', '1px solid #ccc')
      .style('padding', '5px')
      .style('border-radius', '5px')
      .style('pointer-events', 'none');
    
    chartContainer.selectAll('.bar-walc')
      .data(groupedData)
      .enter().append('rect')
      .attr('class', 'bar-walc')
      .attr('x', d => xScale(0)) 
      .attr('y', d => yScale(d.key) - yScale.bandwidth() / 4)
      .attr('width', d => xScale(d.WalcPerCapita) - xScale(0)) 
      .attr('height', yScale.bandwidth() / 2)
      .attr('fill', '#8a89a6')
      .on('mouseover', function(event, d) {
        tooltip.transition().duration(200).style('opacity', 1);
        tooltip.html(`Weekend Consumption : ${d.WalcPerCapita.toFixed(2)}`)
          .style('left', (event.pageX + 5) + 'px')
          .style('top', (event.pageY - 28) + 'px');
      })
      .on('mouseout', function(d) {
        tooltip.transition().duration(500).style('opacity', 0);
      });

    chartContainer.selectAll('.bar-dalc')
      .data(groupedData)
      .enter().append('rect')
      .attr('class', 'bar-dalc')
      .attr('x', d => xScale(0)) 
      .attr('y', d => yScale(d.key) + yScale.bandwidth() / 4)
      .attr('width', d => xScale(d.DalcPerCapita) - xScale(0)) 
      .attr('height', yScale.bandwidth() / 2)
      .attr('fill', '#98abc5')
      .on('mouseover', function(event, d) {
        tooltip.transition().duration(200).style('opacity', 1);
        tooltip.html(`Daily Consumption: ${d.DalcPerCapita.toFixed(2)}`)
          .style('left', (event.pageX + 5) + 'px')
          .style('top', (event.pageY - 28) + 'px');
      })
      .on('mouseout', function(d) {
        tooltip.transition().duration(500).style('opacity', 0);
      });
      

    
    
    chartContainer.selectAll('combined-bar')
      .data(groupedData)
      .enter().append('rect')
      .attr('class', 'bar-walc')
      .attr('x', d => xScale(maxValue)+10) 
      .attr('y', d => yScale(d.key) - yScale.bandwidth() / 4)
      .attr('width', 10) 
      .attr('height', yScale.bandwidth() )
      .attr('fill', '#69b3a2')
      .attr('opacity', 0.7)
      .on('mouseover', function(event, d) {
        d3.select(this)
          .attr('fill', 'orange') // 鼠标悬停时改变颜色
          .attr('opacity', 1); // 鼠标悬停时改变不透明度
          setSelectedBar(d.key); // 更新选中的条
          console.log(`Selected education level: ${d.key}`);
      })
      .on('mouseout', function(event, d) {
        d3.select(this)
          .attr('fill', '#69b3a2') // 恢复原来的颜色
          .attr('opacity', 0.7); // 恢复原来的不透明度
          setSelectedBar(null);
      });

    chartContainer.append('text')
      .attr('x', size.width / 2)
      .attr('y', -10)
      .attr('text-anchor', 'middle')
      .style('font-size', '16px')
      .style('font-weight', 'bold')
      .text('Parental Education vs Alcohol Consumption');

    const legend = chartContainer.append('g')
      .attr('transform', `translate(${size.width - 100}, 20)`);

    legend.append('rect')
      .attr('x', 0)
      .attr('y', 0)
      .attr('width', 10)
      .attr('height', 10)
      .attr('fill', '#98abc5')
      
      
      
    legend.append('text')
      .attr('x', 20)
      .attr('y', 10)
      .text('Daily');

    legend.append('rect')
      .attr('x', 0)
      .attr('y', 20)
      .attr('width', 10)
      .attr('height', 10)
      .attr('fill', '#8a89a6');
    legend.append('text')
      .attr('x', 20)
      .attr('y', 30)
      .text('Weekend');
  }

  return (
    <>
      <div ref={barRef} className='chart-container'>
        <svg id='bar-svg' width='100%' height='500'></svg>
      </div>
    </>
  );
}
