// Homework3/knhu/src/components/BarChart.vue
<script>
import * as d3 from "d3";

export default {
  data() {
    return {
      margin: { top: 40, right: 20, bottom: 100, left: 80 },
      width: 800,
      height: 400,
      selectedMake: null,  // Track selected make for highlighting and filtering
    };
  },
  props: ["onMakeSelect"], // Prop to communicate with other components
  mounted() {
    this.drawChart();
    window.addEventListener("resize", this.drawChart);
  },
  methods: {
    drawChart() {
      const svg = d3.select(this.$refs.svg);
      svg.selectAll("*").remove();

      const width = this.width - this.margin.left - this.margin.right;
      const height = this.height - this.margin.top - this.margin.bottom;

      // Tooltip setup - ensure single instance
      d3.select("body").selectAll(".tooltip").remove();

      const tooltip = d3.select("body").append("div")
        .attr("class", "tooltip")
        .style("position", "absolute")
        .style("background", "#333")
        .style("color", "#fff")
        .style("padding", "8px")
        .style("border-radius", "4px")
        .style("pointer-events", "none")
        .style("opacity", 0); // Initially hidden

      d3.csv('../../data/top_10_car_prices.csv').then(data => {
        const counts = d3.rollups(data, v => v.length, d => d.make)
          .map(([make, count]) => ({ make, count }))
          .sort((a, b) => b.count - a.count)
          .slice(0, 10);

        const x = d3.scaleBand()
          .domain(counts.map(d => d.make))
          .range([0, width])
          .padding(0.1);

        const y = d3.scaleLinear()
          .domain([0, d3.max(counts, d => d.count)])
          .range([height, 0])
          .nice();

        const chart = svg
          .attr("width", this.width)
          .attr("height", this.height)
          .append("g")
          .attr("transform", `translate(${this.margin.left}, ${this.margin.top})`);

        // Bars with load animation and custom tooltip functionality
        chart.selectAll(".bar")
          .data(counts)
          .join("rect")
          .attr("class", "bar")
          .attr("x", d => x(d.make))
          .attr("width", x.bandwidth())
          .attr("y", height) // Start at baseline
          .attr("height", 0) // Start with height 0
          .attr("fill", d => d.make === this.selectedMake ? "orange" : "steelblue")
          .style("cursor", "pointer")
          .transition() // Animate bars growing to their full height
          .duration(1000)
          .attr("y", d => y(d.count))
          .attr("height", d => height - y(d.count));

        // Tooltip interactivity with hover and fade-in/fade-out animations
        chart.selectAll(".bar")
          .on("click", (event, d) => {
            this.selectedMake = this.selectedMake === d.make ? null : d.make;
            this.onMakeSelect(this.selectedMake);
            this.drawChart();
          })
          .on("mouseover", (event, d) => {
            // Highlight selected bar and dim others
            chart.selectAll(".bar")
              .transition()
              .duration(200)
              .attr("fill", bar => bar.make === d.make ? "darkblue" : "lightgrey");

            // Show and position tooltip with additional information
            const total = d3.sum(counts, c => c.count);
            const percentage = ((d.count / total) * 100).toFixed(2);
            tooltip
              .style("opacity", 0)
              .html(`<strong>Make:</strong> ${d.make}<br><strong>Count:</strong> ${d.count}<br><strong>Percentage:</strong> ${percentage}%`)
              .style("left", (event.pageX + 10) + "px")
              .style("top", (event.pageY - 28) + "px")
              .transition()
              .duration(200)
              .style("opacity", 1);
          })
          .on("mousemove", event => {
            tooltip
              .style("left", (event.pageX + 10) + "px")
              .style("top", (event.pageY - 28) + "px");
          })
          .on("mouseout", () => {
            // Reset colors
            chart.selectAll(".bar")
              .transition()
              .duration(200)
              .attr("fill", d => d.make === this.selectedMake ? "orange" : "steelblue");

            // Hide tooltip
            tooltip.transition().duration(200).style("opacity", 0);
          });

        // Add count labels on top of each bar
        chart.selectAll(".label")
          .data(counts)
          .join("text")
          .attr("class", "label")
          .attr("x", d => x(d.make) + x.bandwidth() / 2)
          .attr("y", d => y(d.count) - 5)
          .attr("text-anchor", "middle")
          .style("font-size", "12px")
          .style("fill", "#333")
          .text(d => d.count);

        // X and Y axis
        chart.append("g")
          .attr("transform", `translate(0, ${height})`)
          .call(d3.axisBottom(x))
          .selectAll("text")
          .attr("transform", "rotate(-45)")
          .attr("dx", "-0.6em")
          .attr("dy", "0.6em")
          .style("text-anchor", "end");

        chart.append("g")
          .call(d3.axisLeft(y));

        // Title and labels
        svg.append("text")
          .attr("x", this.width / 2)
          .attr("y", this.margin.top / 2)
          .attr("text-anchor", "middle")
          .style("font-size", "16px")
          .text("Top 10 Car Makes by Sales Count");

        svg.append("text")
          .attr("x", this.width / 2)
          .attr("y", this.height - 10)
          .attr("text-anchor", "middle")
          .style("font-size", "14px")
          .text("Car Make");

        svg.append("text")
          .attr("transform", "rotate(-90)")
          .attr("x", -height / 2)
          .attr("y", this.margin.left / 4)
          .attr("text-anchor", "middle")
          .style("font-size", "14px")
          .text("Count");
      });
    },
  },
  watch: {
    selectedMake() {
      this.drawChart();
    }
  }
};
</script>

<template>
  <svg ref="svg"></svg>
</template>

<style scoped>
.bar {
  transition: fill 0.2s;
}
.bar:hover {
  fill: darkblue;
}
.label {
  font-weight: bold;
  fill: #000;
}
/* Style for the custom tooltip */
.tooltip {
  font-size: 14px;
  line-height: 1.5;
  opacity: 0;
  transition: opacity 0.2s ease;
}
</style>

// Homework3/yuhwei/src/components/BarChart.tsx
import React, { useEffect, useState, useRef } from 'react';
import * as d3 from 'd3';
import { isEmpty, max } from 'lodash';
import { useResizeObserver, useDebounceCallback } from 'usehooks-ts';
import { ComponentSize, Margin } from '../types';

export default function Example({ selectedBar, setSelectedBar }) {
  const [bars, setBars] = useState([]);
  const barRef = useRef<HTMLDivElement>(null);
  const [size, setSize] = useState<ComponentSize>({ width: 0, height: 0 });
  const margin: Margin = { top: 20, right: 150, bottom: 100, left: 150 }; 
  const onResize = useDebounceCallback((size: ComponentSize) => setSize(size), 20);
  const [stacked, setStacked] = useState(false);


  useResizeObserver({ ref: barRef, onResize });

  useEffect(() => {
    const dataFromCSV = async () => {
      try {
        const csvData = await d3.csv('../../data/student-por.csv', d => ({
          totalEdu: +d.Medu + +d.Fedu, 
          Dalc: +d.Dalc, 
          Walc: +d.Walc 
        }));
        setBars(csvData);
      } catch (error) {
        console.error('Error loading CSV:', error);
      }
    };
    dataFromCSV();
  }, []);

  useEffect(() => {
    if (isEmpty(bars)) return;
    if (size.width === 0 || size.height === 0) return;
    d3.select('#bar-svg').selectAll('*').remove();
    initChart();
  }, [bars, size]);

  function initChart() {
    const chartContainer = d3.select('#bar-svg');

    const groupedData = d3.rollups(
      bars,
      v => ({
        DalcPerCapita: d3.sum(v, d => d.Dalc) / v.length,
        WalcPerCapita: d3.sum(v, d => d.Walc) / v.length,
      }),
      d => {
        const totalEdu = d.totalEdu;
        if (totalEdu <= 2) return '0-2';
        if (totalEdu <= 5) return '3-5';
        if (totalEdu <= 8) return '6-8';
        return '9+';
      }
    ).map(([key, value]) => ({ key, ...value }))
     .sort((a, b) => ['0-2', '3-5', '6-8', '9+'].indexOf(a.key) - ['0-2', '3-5', '6-8', '9+'].indexOf(b.key));

    const minValue = d3.min(groupedData, d => Math.min(d.DalcPerCapita, d.WalcPerCapita));
    const maxValue = d3.max(groupedData, d => Math.max(d.DalcPerCapita, d.WalcPerCapita));

    const xScale = d3.scaleLinear()
      .domain([0, maxValue]) 
      .range([margin.left, size.width - margin.right]);

    const yScale = d3.scaleBand()
      .domain(groupedData.map(d => d.key))
      .range([size.height - margin.bottom, margin.top])
      .padding(0.4);

    chartContainer.append('g')
      .attr('transform', `translate(0, ${size.height - margin.bottom})`)
      .call(d3.axisBottom(xScale));

    chartContainer.append('text')
      .attr('transform', `translate(${(size.width - margin.left) / 2 + margin.left}, ${size.height - margin.bottom + 40})`)
      .style('text-anchor', 'middle')
      .text('Alcohol Consumption');

    chartContainer.append('g')
      .attr('transform', `translate(${margin.left}, 0)`)
      .call(d3.axisLeft(yScale));

    chartContainer.append('text')
      .attr('transform', 'rotate(-90)')
      .attr('y', margin.left - 60)
      .attr('x', -(size.height / 2))
      .attr('dy', '1em')
      .style('text-anchor', 'middle')
      .text('Parental Education Levels');
    
    const tooltip = d3.select(barRef.current)
      .append('div')
      .attr('class', 'tooltip')
      .style('opacity', 0)
      .style('position', 'absolute')
      .style('background', 'white')
      .style('border', '1px solid #ccc')
      .style('padding', '5px')
      .style('border-radius', '5px')
      .style('pointer-events', 'none');
    
    chartContainer.selectAll('.bar-walc')
      .data(groupedData)
      .enter().append('rect')
      .attr('class', 'bar-walc')
      .attr('x', d => xScale(0)) 
      .attr('y', d => yScale(d.key) - yScale.bandwidth() / 4)
      .attr('width', d => xScale(d.WalcPerCapita) - xScale(0)) 
      .attr('height', yScale.bandwidth() / 2)
      .attr('fill', '#8a89a6')
      .on('mouseover', function(event, d) {
        tooltip.transition().duration(200).style('opacity', 1);
        tooltip.html(`Weekend Consumption : ${d.WalcPerCapita.toFixed(2)}`)
          .style('left', (event.pageX + 5) + 'px')
          .style('top', (event.pageY - 28) + 'px');
      })
      .on('mouseout', function(d) {
        tooltip.transition().duration(500).style('opacity', 0);
      });

    chartContainer.selectAll('.bar-dalc')
      .data(groupedData)
      .enter().append('rect')
      .attr('class', 'bar-dalc')
      .attr('x', d => xScale(0)) 
      .attr('y', d => yScale(d.key) + yScale.bandwidth() / 4)
      .attr('width', d => xScale(d.DalcPerCapita) - xScale(0)) 
      .attr('height', yScale.bandwidth() / 2)
      .attr('fill', '#98abc5')
      .on('mouseover', function(event, d) {
        tooltip.transition().duration(200).style('opacity', 1);
        tooltip.html(`Daily Consumption: ${d.DalcPerCapita.toFixed(2)}`)
          .style('left', (event.pageX + 5) + 'px')
          .style('top', (event.pageY - 28) + 'px');
      })
      .on('mouseout', function(d) {
        tooltip.transition().duration(500).style('opacity', 0);
      });
      

    
    
    chartContainer.selectAll('combined-bar')
      .data(groupedData)
      .enter().append('rect')
      .attr('class', 'bar-walc')
      .attr('x', d => xScale(maxValue)+10) 
      .attr('y', d => yScale(d.key) - yScale.bandwidth() / 4)
      .attr('width', 10) 
      .attr('height', yScale.bandwidth() )
      .attr('fill', '#69b3a2')
      .attr('opacity', 0.7)
      .on('mouseover', function(event, d) {
        d3.select(this)
          .attr('fill', 'orange') // 鼠标悬停时改变颜色
          .attr('opacity', 1); // 鼠标悬停时改变不透明度
          setSelectedBar(d.key); // 更新选中的条
          console.log(`Selected education level: ${d.key}`);
      })
      .on('mouseout', function(event, d) {
        d3.select(this)
          .attr('fill', '#69b3a2') // 恢复原来的颜色
          .attr('opacity', 0.7); // 恢复原来的不透明度
          setSelectedBar(null);
      });

    chartContainer.append('text')
      .attr('x', size.width / 2)
      .attr('y', -10)
      .attr('text-anchor', 'middle')
      .style('font-size', '16px')
      .style('font-weight', 'bold')
      .text('Parental Education vs Alcohol Consumption');

    const legend = chartContainer.append('g')
      .attr('transform', `translate(${size.width - 100}, 20)`);

    legend.append('rect')
      .attr('x', 0)
      .attr('y', 0)
      .attr('width', 10)
      .attr('height', 10)
      .attr('fill', '#98abc5')
      
      
      
    legend.append('text')
      .attr('x', 20)
      .attr('y', 10)
      .text('Daily');

    legend.append('rect')
      .attr('x', 0)
      .attr('y', 20)
      .attr('width', 10)
      .attr('height', 10)
      .attr('fill', '#8a89a6');
    legend.append('text')
      .attr('x', 20)
      .attr('y', 30)
      .text('Weekend');
  }

  return (
    <>
      <div ref={barRef} className='chart-container'>
        <svg id='bar-svg' width='100%' height='500'></svg>
      </div>
    </>
  );
}
