// Homework2/qqai13/src/components/sankey.tsx
import React, { useEffect, useRef, useState } from 'react';
import * as d3 from 'd3';
import { sankey as d3Sankey, sankeyLinkHorizontal } from 'd3-sankey';

const SankeyDiagram = () => {
  const svgRef = useRef();
  const [data, setData] = useState(null);

  useEffect(() => {
    // Load CSV data
    const loadData = async () => {
      try {
        const csvData = await d3.csv('/data/financial_risk_assessment.csv');
        setData(csvData);
      } catch (error) {
        console.error('Error loading CSV data:', error);
      }
    };
    loadData();
  }, []);

  useEffect(() => {
    if (!data) return;

    const sankeyData = processDataForSankey(data);

    // Get container dimensions
    const container = svgRef.current.parentElement;
    const width = container.clientWidth;
    const height = container.clientHeight || 600; // Default height if not set

    // Create SVG canvas
    const svg = d3.select(svgRef.current)
      .attr('viewBox', `0 0 ${width} ${height}`)
      .attr('preserveAspectRatio', 'xMidYMid meet');

    // Clear any existing content
    svg.selectAll('*').remove();

    // Add Title
    svg.append('text')
      .attr('x', width / 2)
      .attr('y', 30)
      .attr('text-anchor', 'middle')
      .style('font-size', '24px')
      .style('font-family', 'monospace')
      .style('font-weight', 'bold')
      .text('Sankey Diagram: Gender to Risk Rating');

    // Create Sankey generator
    const sankeyGenerator = d3Sankey()
      .nodeId(d => d.id)
      .nodeWidth(15)
      .nodePadding(10)
      .extent([[1, 50], [width - 1, height - 6]]); // Adjusted to account for title height

    // Generate Sankey data
    const { nodes, links } = sankeyGenerator({
      nodes: sankeyData.nodes.map(d => Object.assign({}, d)),
      links: sankeyData.links.map(d => Object.assign({}, d)),
    });

    // Define color scale
    const color = d3.scaleOrdinal(d3.schemeCategory10);

    // Add links
    svg.append('g')
      .attr('transform', 'translate(0,20)') // Adjust if needed
      .selectAll('path')
      .data(links)
      .join('path')
      .attr('d', sankeyLinkHorizontal())
      .attr('fill', 'none')
      .attr('stroke', d => color(d.source.id))
      .attr('stroke-width', d => Math.max(1, d.width))
      .attr('stroke-opacity', 0.5);

    // Add nodes
    svg.append('g')
      .attr('transform', 'translate(0,20)') // Adjust if needed
      .selectAll('rect')
      .data(nodes)
      .join('rect')
      .attr('x', d => d.x0)
      .attr('y', d => d.y0)
      .attr('height', d => d.y1 - d.y0)
      .attr('width', d => d.x1 - d.x0)
      .attr('fill', d => color(d.id))
      .attr('stroke', '#000')
      .append('title')
      .text(d => `${d.id}\n${d.value}`)
      .style('font-family', 'monospace');

    // Add node labels
    svg.append('g')
      .attr('transform', 'translate(0,20)') // Adjust if needed
      .selectAll('text')
      .data(nodes)
      .join('text')
      .attr('x', d => d.x0 - 6)
      .attr('y', d => (d.y1 + d.y0) / 2)
      .attr('dy', '0.35em')
      .attr('text-anchor', 'end')
      .text(d => d.id)
      .style('font-family', 'monospace')
      .filter(d => d.x0 < width / 2)
      .attr('x', d => d.x1 + 6)
      .attr('text-anchor', 'start');

  }, [data]);

  // Data processing function remains the same, but with normalization
  const processDataForSankey = (csvData) => {
    const nodesSet = new Set();
    const linksMap = new Map();

    csvData.forEach((row) => {
      // Extract and normalize the relevant fields
      const gender = row['Gender']?.trim().toLowerCase();
      const education = row['Education Level']?.trim().toLowerCase();
      const employment = row['Employment Status']?.trim().toLowerCase();
      const risk = row['Risk Rating']?.trim().toLowerCase();

      // Ensure all fields are present
      if (gender && education && employment && risk) {
        // Add nodes to the set
        nodesSet.add(gender);
        nodesSet.add(education);
        nodesSet.add(employment);
        nodesSet.add(risk);

        // Define link pairs
        const linkPairs = [
          [gender, education],
          [education, employment],
          [employment, risk],
        ];

        // Aggregate link values
        linkPairs.forEach(([source, target]) => {
          const key = `${source}->${target}`;
          if (linksMap.has(key)) {
            linksMap.get(key).value += 1;
          } else {
            linksMap.set(key, { source, target, value: 1 });
          }
        });
      }
    });

    // Convert nodes set to array of objects
    const nodes = Array.from(nodesSet).map((id) => ({ id }));
    // Convert links map to array
    const links = Array.from(linksMap.values());

    console.log('Links:', links); // For debugging

    return { nodes, links };
  };

  return (
    <div style={{ width: '100%', height: '600px', marginBottom: '60px' }}> {/* Set a default height */}
      <svg ref={svgRef} style={{ width: '100%', height: '100%'  }}></svg>
    </div>
  );
};

export default SankeyDiagram;

// Homework3/davchu/src/components/Sankey.vue
<script lang="ts">
import * as d3 from "d3";
import { sankey, sankeyLinkHorizontal, SankeyGraph, SankeyNode, SankeyLink } from "d3-sankey";
import { debounce, isEmpty } from 'lodash';

export default {
  data() {
    return {
      data: [] as any[], // Store the CSV data
      sankeyData: {} as SankeyGraph<any, any>, // Data structure for Sankey diagram
      size: { width: 0, height: 0 }, // Chart size
      margin: { left: 50, right: 50, top: 50, bottom: 50 }, // Adjust margins
      validBodyTypes: ['sedan', 'suv', 'truck', 'coupe', 'hatchback'], // List of valid body types
      selectedState: null, // Track the selected state
      stateColorMap: new Map() // Store unique color mappings for each state
    };
  },
  computed: {
    rerender() {
      return !isEmpty(this.sankeyData) && this.size.width > 0 && this.size.height > 0;
    }
  },
  created() {
    // Load and process CSV data
    d3.csv('../../data/car_prices.csv').then((data) => {
      this.data = this.preprocessData(data); // Preprocess the data
      this.processData(); // Structure data for Sankey
      this.initChart(); // Initialize the Sankey diagram after loading data
    });
  },
  methods: {
    onResize() {
      const container = this.$refs.sankeyContainer as HTMLElement;
      this.size.width = container.clientWidth;
      this.size.height = container.clientHeight;
    },
    preprocessData(data: any[]) {
      // Filter for valid entries:
      // - state must be two lowercase letters
      // - body must be in validBodyTypes
      // - year, state, and body should not be missing
      return data.filter(d => 
        /^[a-z]{2}$/.test(d.state) && 
        this.validBodyTypes.includes(d.body) &&
        d.state && d.year && d.body
      );
    },
    processData() {
      // Process data to create nodes and links for Sankey layout
      const stateYearBodyTypeCounts = d3.rollups(
        this.data,
        v => v.length,
        d => d.state, // First level: State
        d => d.year,  // Second level: Year
        d => d.body // Third level: Body type
      );

      // Generate Sankey nodes and links from hierarchical data
      const nodes: SankeyNode<any, any>[] = [];
      const links: SankeyLink<any, any>[] = [];

      const nodeMap = new Map();

      // Helper function to add nodes and links
      const addNode = (name: string) => {
        if (!nodeMap.has(name)) {
          const node = { name };
          nodeMap.set(name, nodes.length);
          nodes.push(node);
        }
        return nodeMap.get(name);
      };

      stateYearBodyTypeCounts.forEach(([state, yearGroups]) => {
        const stateNode = addNode(state);

        yearGroups.forEach(([year, bodyGroups]) => {
          const yearNode = addNode(`Year ${year}`);
          links.push({ source: stateNode, target: yearNode, value: d3.sum(bodyGroups, d => d[1]) });

          bodyGroups.forEach(([bodyType, count]) => {
            const bodyTypeNode = addNode(bodyType);
            links.push({ source: yearNode, target: bodyTypeNode, value: count });
          });
        });
      });

      this.sankeyData = { nodes, links };

      // Generate a color scale for states
      const uniqueStates = Array.from(new Set(this.data.map(d => d.state)));
      const colorScale = d3.scaleOrdinal(d3.schemeCategory10); // You can use any other color scale
      uniqueStates.forEach((state, index) => {
        this.stateColorMap.set(state, colorScale(index));
      });
    },
    initChart() {
    const svg = d3.select("#sankey-svg")
      .attr("width", this.size.width)
      .attr("height", this.size.height)
      .attr("viewBox", `0 0 ${this.size.width} ${this.size.height}`);
    
    const chartContainer = svg.append("g")
      .attr("transform", `translate(${this.margin.left}, ${this.margin.top})`);

    // Add title text at the top of the chart
    svg.append("text")
      .attr("x", this.size.width / 2)  // Center the title horizontally
      .attr("y", this.margin.top / 2)  // Position it a little above the graph
      .attr("text-anchor", "middle")
      .style("font-size", "16px")
      .style("font-weight", "bold")
      .text("Car Sales Flow by State, Year, and Body Type (Click to highlight links)");

    const sankeyLayout = sankey<any, any>()
      .nodeWidth(15)
      .nodePadding(10)
      .extent([[0, 0], [this.size.width - this.margin.left - this.margin.right, this.size.height - this.margin.top - this.margin.bottom]]);

    const sankeyGraph = sankeyLayout(this.sankeyData);

    // Draw links
    const link = chartContainer.append("g")
      .selectAll("path")
      .data(sankeyGraph.links)
      .enter()
      .append("path")
      .attr("d", sankeyLinkHorizontal())
      .attr("fill", "none")
      .attr("stroke", d => d3.interpolateBlues(d.value / 100))
      .attr("stroke-width", d => Math.max(1, d.width))
      .attr("opacity", 0.5);

    // Draw nodes
    const node = chartContainer.append("g")
      .selectAll("rect")
      .data(sankeyGraph.nodes)
      .enter()
      .append("rect")
      .attr("x", d => d.x0)
      .attr("y", d => d.y0)
      .attr("height", d => d.y1 - d.y0)
      .attr("width", d => d.x1 - d.x0)
      .attr("fill", d => {
        // Apply color to the state nodes
        return this.stateColorMap.has(d.name) ? this.stateColorMap.get(d.name) : "gray";
      })
      .attr("stroke", "black")
      .style("cursor", "pointer") // Make the nodes clickable
      .on("click", (event, d) => this.handleClick(d, link, node)); // Add click event listener

    // Add node labels with adjusted positioning
    node.append("title").text(d => `${d.name}\n${d.value.toLocaleString()}`);

    chartContainer.append("g")
      .selectAll("text")
      .data(sankeyGraph.nodes)
      .enter()
      .append("text")
      .attr("x", d => d.x0 - 10) // Position text to the left of the node
      .attr("y", d => (d.y0 + d.y1) / 2) // Center text vertically
      .attr("text-anchor", "end") // Align text to the right (left-aligned relative to the node)
      .style("font-size", "10px")
      .style("alignment-baseline", "middle")
      .text(d => d.name);
  }
,

    handleClick(nodeData, link, node) {
      const selectedState = nodeData.name;

      // If the clicked state is the same as the selected one, reset everything
      if (this.selectedState === selectedState) {
        this.selectedState = null;
        node.style("opacity", 1);
        link.style("opacity", 0.5);
      } else {
        this.selectedState = selectedState;

        // Dim all other nodes and links
        node.style("opacity", 0.1);
        link.style("opacity", 0.1);

        // Highlight the selected state, and its related links to Year and Body Type
        node.filter(d => d.name === selectedState).style("opacity", 1);
        
        // Highlight links connected to the selected state, both to year and body type
        link.filter(d => d.source.name === selectedState || d.target.name === selectedState)
            .style("opacity", 1);

        // Ensure all relevant year and body type nodes are highlighted, even if not the source
        node.filter(d => d.name === "Year" || this.validBodyTypes.includes(d.name)).style("opacity", 1);
      }
    }
  },
  watch: {
    rerender(newSize) {
      if (newSize) {
        d3.select('#sankey-svg').selectAll('*').remove(); // Clear previous chart elements
        this.initChart();
      }
    }
  },
  mounted() {
    window.addEventListener('resize', debounce(this.onResize, 100));
    this.onResize(); // Initialize size on mount
  },
  beforeDestroy() {
    window.removeEventListener('resize', this.onResize);
  }
}
</script>

<template>
  <div class="chart-container" ref="sankeyContainer" style="width: 100vw; height: 100vh;">
    <svg id="sankey-svg"></svg>
  </div>
</template>

<style scoped>
.chart-container {
  display: flex;
  width: 100%;
  height: 100%;
  justify-content: center;
  align-items: center;
}
</style>
